# Generated by Django 5.0.6 on 2024-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
