# Generated by Django 5.0.6 on 2024-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('contact_number', models.CharField(max_length=15)),
                ('acres_ploughed', models.FloatField()),
                ('season', models.CharField(max_length=50)),
                ('crop_grown', models.CharField(max_length=100)),
                ('seeds_used', models.CharField(max_length=50)),
                ('date_seed_sown', models.DateField()),
                ('transplanting', models.CharField(max_length=100)),
                ('irrigation_method', models.CharField(max_length=100)),
                ('fertilizers_used', models.CharField(max_length=100)),
                ('date_harvesting', models.DateField()),
                ('subfield', models.CharField(max_length=100)),
                ('variety_used', models.CharField(max_length=100)),
                ('quantity_used', models.CharField(max_length=50)),
                ('irrigation_type', models.CharField(max_length=100)),
                ('fertilizers_type', models.CharField(max_length=100)),
            ],
        ),
    ]
